openapi: 3.0.3
info:
  title: Retailer API [DRAFT]
  version: 1.0.1
  description: |-
    This is the official OpenAPI specification for Retailer API V1.

    ## Concepts
    - **OMS (Order Management System)**: A software system used to manage and track customer orders, from receiving the order to delivering the items to the customer.
    - **Picking Location**: The physical location within a warehouse, distribution centre or store where the items for an order are prepared for delivery. It is the place where products are stored, organized and picked.
    - **Order**: a customer's request to purchase one or more articles. An order includes the customer's selected articles, shipping information, some customer preferences, and the preferred Timeslot. It will be tracked by a unique order ID and will transition between different statuses. Depending on the company's policies, orders can also be canceled, refunded or modified.
    - **Timeslot**: a timeslot is a specific window of time during which a customer can pick up their order or receive a delivery. Timeslots are usually divided into particular intervals, such as every hour or every two hours. The system may offer different timeslots depending on the picking location, days of the week, or other factors. Customers can select a timeslot when placing their order; availability can change depending on the demand.
    - **Shopper**: An individual responsible for fulfilling an order by picking the products and preparing them for delivery.
    - **Order status**: The current stage of an order, reflecting its progress and whether it is confirmed, assigned, in transit, delivered, on hold, rejected, canceled, or returned.
    - **Item status**: The current stage of an individual item within an order, reflecting its progress and whether it is pending, picked, not found, or replaced.
    - **Order rescheduling**: The process of moving an order to a different timeslot, usually due to a change in delivery availability or customer preference.
    - **Event**: An occurrence or change in the state of an order, such as receipt of the order, confirmation, assignment, delivery, or cancellation, that can trigger a webhook notification to subscribed parties.

    ## Webhooks

    Webhooks allow your application to subscribe to specific events that occur within the API.
    Our API includes webhooks to notify you of status changes on an order.
    By subscribing to these webhooks, you can receive real-time updates on the status of your orders, without the need to continuously poll the API.

    <img src="http://lolamarket.statics.prod.s3.amazonaws.com/lola-help/order_state_machine.jpg" />
    1. `order.received`: Order received on the OMS and waiting for processing.
    2. `order.confirmed`: Order confirmed by the OMS, waiting for shopper assignment.
    3. `order.allocated`: Order assigned and accepted by a shopper. In some cases, the order may be assigned to multiple resources (picker, courier).
    4. `order.rescheduled`: Order has been moved to a different timeslot, needs to be allocated.
    5. `order.in.picking`: Shopper started picking items. Each product in the order will have their own status.
        1. `item.pending`
        2. `item.picked`
        3. `item.not.found`
        4. `item.replaced`
    6. `order.picked`: Shopper finished picking order items and will go to the cashier.
    7. `order.in.transit`: Order on its way to the customer.
    8. `order.delivered`: Order delivered to the customer.
    9. `order.on.hold`: Order on hold for some reason that may include:
        1. In warehouse: order with partial picking for some reason.
        2. Fraud detected: Retailer detects a fraud attempt by the shopper and order has been blocked.
        3. Order not delivered: Order can not be delivered to the customer and delivery has been postponed.
    10. `order.rejected`: Order rejected by the OMS for some reason.
    11. `order.canceled`: Order has been canceled before left the store. A cancelation could be initiated by the customer, the retailer, the shopper, or the OMS
    12. `order.returned`: Order has been canceled after leaving the store so need to be returned to picking location.

    In the following sections, you will find examples of the payload for each event type that can be triggered by an order status change.

    ### ORDER_RECEIVED
    Order received on the OMS and waiting for processing.
    ```json
    {
      "eventId": 1201895966044343901,
      "eventName": "order.received",
      "eventTimestamp": "2023-01-10T18:30:00Z",
      "eventPayload": {
        "orderId": "b7fab7ae-11fc-4453-98e1-a2f5421a2b81",
        "pickingLocation": {
           "id": "123",
           "name": "NORTH-21242"
        },
        "timeSlot": {
          "id": "slot1",
          "fromDate": "2023-01-11T14:00:00+00:00",
          "toDate": "2023-01-11T15:00:00+00:00"
        },
        "serviceType": "DELIVERY",
        "express": false
      }
    }
    ```

    ### ORDER_CONFIRMED
    Order confirmed by the OMS, waiting for shopper assignment.
    ```json
    {
      "eventId": 1201895966044343902,
      "eventName": "order.confirmed",
      "eventTimestamp": "2023-01-10T18:31:00Z",
      "eventPayload": {
        "orderId": "b7fab7ae-11fc-4453-98e1-a2f5421a2b81",
        "pickingLocation": {
           "id": "123",
           "name": "NORTH-21242"
        },
        "timeSlot": {
          "id": "slot1",
          "fromDate": "2023-01-11T14:00:00+00:00",
          "toDate": "2023-01-11T15:00:00+00:00"
        },
        "serviceType": "DELIVERY",
        "express": false
      }
    }
    ```

    ### ORDER_ALLOCATED
    Order assigned and accepted by a shopper. In some cases, the order may be assigned to multiple resources (picker, courier).
    ```json
    {
      "eventId": 1201895966044343903,
      "eventName": "order.allocated",
      "eventTimestamp": "2023-01-11T12:50:00Z",
      "eventPayload": {
        "orderId": "b7fab7ae-11fc-4453-98e1-a2f5421a2b81",
        "pickingLocation": {
           "id": "123",
           "name": "NORTH-21242"
        },
        "timeslot": {
          "id": "slot1",
          "fromDate": "2023-01-11T14:00:00+00:00",
          "toDate": "2023-01-11T15:00:00+00:00"
        },
        "shopper": {
          "id": "shopper-01",
          "name": "Lukasz",
          "avatarUrl": "https:\/\/media.lolamarket.com\/shopper\/lsdfdsf-sfdfs123-asd2.jpg"
        },
        "serviceType": "DELIVERY",
        "express": false
      }
    }
    ```

    ### ORDER_RESCHEDULED
    Order has been moved to a different timeslot, needs to be allocated.
    ```json
    {
      "eventId": 1201895966044343904,
      "eventName": "order.rescheduled",
      "eventTimestamp": "2023-01-11T13:50:00Z",
      "eventPayload": {
        "orderId": "b7fab7ae-11fc-4453-98e1-a2f5421a2b81",
        "pickingLocation": {
           "id": "123",
           "name": "NORTH-21242"
        },
        "newTimeslot": {
          "id": "slot45",
          "fromDate": "2023-01-12T10:00:00+00:00",
          "toDate": "2023-01-12T11:00:00+00:00"
        },
        "serviceType": "DELIVERY",
        "express": false
      }
    }
    ```

    ### ORDER_IN_PICKING
    Shopper started picking items. Each product in the order will have their own status.
    ```json
    {
      "eventId": 1201895966044343905,
      "eventName": "order.in.picking",
      "eventTimestamp": "2023-01-12T09:10:20Z",
      "eventPayload": {
        "orderId": "b7fab7ae-11fc-4453-98e1-a2f5421a2b81",
        "pickingLocation": {
           "id": "123",
           "name": "NORTH-21242"
        },
        "timeslot": {
          "id": "slot45",
          "fromDate": "2023-01-12T10:00:00+00:00",
          "toDate": "2023-01-12T11:00:00+00:00"
        },
        "shopper": {
          "id": "shopper-01",
          "name": "Lukasz",
          "avatarUrl": "https:\/\/media.lolamarket.com\/shopper\/lsdfdsf-sfdfs123-asd2.jpg"
        },
        "serviceType": "DELIVERY",
        "express": false
      }
    }
    ```

    ### ORDER_PICKED
    Shopper finished picking order items and will go to the cashier.
    ```json
    {
      "eventId": 1201895966044343906,
      "eventName": "order.picked",
      "eventTimestamp": "2023-01-12T10:12:31Z",
      "eventPayload": {
        "orderId": "b7fab7ae-11fc-4453-98e1-a2f5421a2b81",
        "pickingLocation": {
           "id": "123",
           "name": "NORTH-21242"
        },
        "timeslot": {
          "id": "slot45",
          "fromDate": "2023-01-12T10:00:00+00:00",
          "toDate": "2023-01-12T11:00:00+00:00"
        },
        "shopper": {
          "id": "shopper-01",
          "name": "Lukasz",
          "avatarUrl": "https:\/\/media.lolamarket.com\/shopper\/lsdfdsf-sfdfs123-asd2.jpg"
        },
        "serviceType": "DELIVERY",
        "express": false,
        "articles": [
          {
            "itemId": "12345",
            "scanCode": "00980349940",
            "quantityRequested": 2.0,
            "quantityRequestedUnit": "unit",
            "quantityFulfilled": 1.0,
            "quantityFulfilledUnit": "unit",
            "replaced": false
          },
          {
            "itemId": "12346",
            "scanCode": "00980349941",
            "quantityRequested": 2.0,
            "quantityRequestedUnit": "unit",
            "quantityFulfilled": 1.0,
            "quantityFulfilledUnit": "unit",
            "replaced": true,
            "replacement": {
              "itemId": "12345"
            }
          },
          {
            "itemId": "12347",
            "scanCode": "",
            "quantityRequested": 5.0,
            "quantityRequestedUnit": "unit",
            "quantityFulfilled": 0.430,
            "quantityFulfilledUnit": "kilograms",
            "replaced": true,
            "replacement": {
              "itemId": "12",
              "shopperProvidedName": "Oranges",
              "shopperProvidedPrice": 1.23
            }
          }
        ],
        "bagsCount": 1
      }
    }
    ```

    ### ORDER_IN_TRANSIT
    Order on its way to the customer.
    ```json
    {
      "eventId": 1201895966044343907,
      "eventName": "order.in.transit",
      "eventTimestamp": "2023-01-12T10:18:12Z",
      "eventPayload": {
        "orderId": "b7fab7ae-11fc-4453-98e1-a2f5421a2b81",
        "pickingLocation": {
           "id": "123",
           "name": "NORTH-21242"
        },
        "timeslot": {
          "id": "slot45",
          "fromDate": "2023-01-12T10:00:00+00:00",
          "toDate": "2023-01-12T11:00:00+00:00"
        },
        "shopper": {
          "id": "shopper-01",
          "name": "Lukasz",
          "avatarUrl": "https:\/\/media.lolamarket.com\/shopper\/lsdfdsf-sfdfs123-asd2.jpg"
        },
        "serviceType": "DELIVERY",
        "express": false,
        "articles": [
          {
            "itemId": "12345",
            "scanCode": "00980349940",
            "quantityRequested": 2.0,
            "quantityRequestedUnit": "unit",
            "quantityFulfilled": 1.0,
            "quantityFulfilledUnit": "unit",
            "replaced": false
          },
          {
            "itemId": "12346",
            "scanCode": "00980349941",
            "quantityRequested": 2.0,
            "quantityRequestedUnit": "unit",
            "quantityFulfilled": 1.0,
            "quantityFulfilledUnit": "unit",
            "replaced": true,
            "replacement": {
              "itemId": "12345"
            }
          },
          {
            "itemId": "12347",
            "scanCode": "",
            "quantityRequested": 5.0,
            "quantityRequestedUnit": "unit",
            "quantityFulfilled": 0.430,
            "quantityFulfilledUnit": "kilograms",
            "replaced": true,
            "replacement": {
              "itemId": "12",
              "shopperProvidedName": "Oranges",
              "shopperProvidedPrice": 1.23
            }
          }
        ],
        "bagsCount": 1
      }
    }
    ```

    ### ORDER_DELIVERED
    Order delivered to the customer.
    ```json
    {
      "eventId": 1201895966044343908,
      "eventName": "order.delivered",
      "eventTimestamp": "2023-01-12T10:43:11Z",
      "eventPayload": {
        "orderId": "b7fab7ae-11fc-4453-98e1-a2f5421a2b81",
        "pickingLocation": {
           "id": "123",
           "name": "NORTH-21242"
        },
        "timeslot": {
          "id": "slot45",
          "fromDate": "2023-01-12T10:00:00+00:00",
          "toDate": "2023-01-12T11:00:00+00:00"
        },
        "shopper": {
          "id": "shopper-01",
          "name": "Lukasz",
          "avatarUrl": "https:\/\/media.lolamarket.com\/shopper\/lsdfdsf-sfdfs123-asd2.jpg"
        },
        "serviceType": "DELIVERY",
        "express": false,
        "articles": [
          {
            "itemId": "12345",
            "scanCode": "00980349940",
            "quantityRequested": 2.0,
            "quantityRequestedUnit": "unit",
            "quantityFulfilled": 1.0,
            "quantityFulfilledUnit": "unit",
            "replaced": false
          },
          {
            "itemId": "12346",
            "scanCode": "00980349941",
            "quantityRequested": 2.0,
            "quantityRequestedUnit": "unit",
            "quantityFulfilled": 1.0,
            "quantityFulfilledUnit": "unit",
            "replaced": true,
            "replacement": {
              "itemId": "12345"
            }
          },
          {
            "itemId": "12347",
            "scanCode": "",
            "quantityRequested": 5.0,
            "quantityRequestedUnit": "unit",
            "quantityFulfilled": 0.430,
            "quantityFulfilledUnit": "kilograms",
            "replaced": true,
            "replacement": {
              "itemId": "12",
              "shopperProvidedName": "Oranges",
              "shopperProvidedPrice": 1.23
            }
          }
        ],
        "bagsCount": 1
      }
    }
    ```

    ### ORDER_ON_HOLD
    Order on hold for some reason that may include:
    ```json
    {
      "eventId": 1201895966044343909,
      "eventName": "order.onHold",
      "eventTimestamp": "2023-01-12T10:34:11Z",
      "eventPayload": {
        "orderId": "b7fab7ae-11fc-4453-98e1-a2f5421a2b81",
        "pickingLocation": {
           "id": "123",
           "name": "NORTH-21242"
        },
        "timeSlot": {
          "id": "slot1",
          "fromDate": "2023-01-11T14:00:00+00:00",
          "toDate": "2023-01-11T15:00:00+00:00"
        },
        "reason": {
          "code": "CUSTOMER_NO_SHOW",
          "description": "Customer not abailable at delivery location."
        },
        "serviceType": "DELIVERY",
        "express": false
      }
    }
    ```

    ### ORDER_REJECTED
    Order rejected by the OMS for some reason.
    ```json
    {
      "eventId": 1201895966044343910,
      "eventName": "order.rejected",
      "eventTimestamp": "2023-01-11T19:00:00Z",
      "eventPayload": {
        "orderId": "b7fab7ae-11fc-4453-98e1-a2f5421a2b81",
        "reason": {
          "code": "TIMESLOT_NOT_AVAILABLE",
          "description": "The timeslot provided is not available."
        },
        "serviceType": "DELIVERY",
        "express": false
      }
    }
    ```

    ### ORDER_CANCELED
    Order has been canceled before left the store. A cancelation could be initiated by the customer, the retailer, the shopper, or the OMS
    ```json
    {
      "eventId": 1201895966044343911,
      "eventName": "order.canceled",
      "eventTimestamp": "2023-01-11T19:00:00Z",
      "eventPayload": {
        "orderId": "b7fab7ae-11fc-4453-98e1-a2f5421a2b81",
        "pickingLocation": {
           "id": "123",
           "name": "NORTH-21242"
        },
        "reason": {
          "code": "PICKING_LOCATION_NOT_AVAILABLE",
          "description": "Picking location is not available."
        },
        "serviceType": "DELIVERY",
        "express": false
      }
    }
    ```

    ### ORDER_RETURNED
    Order has been canceled after leaving the store so need to be returned to picking location.
    ```json
    {
      "eventId": 1201895966044343912,
      "eventName": "order.returned",
      "eventTimestamp": "2023-01-12T19:00:00Z",
      "eventPayload": {
        "orderId": "b7fab7ae-11fc-4453-98e1-a2f5421a2b81",
        "pickingLocation": {
           "id": "123",
           "name": "NORTH-21242"
        },
        "reason": {
          "code": "CUSTOMER_NO_SHOW",
          "description": "Customer not abailable at delivery location."
        },
        "serviceType": "DELIVERY",
        "express": false,
        "articles": [
          {
            "itemId": "12345",
            "scanCode": "00980349940",
            "quantityRequested": 2.0,
            "quantityRequestedUnit": "unit",
            "quantityFulfilled": 1.0,
            "quantityFulfilledUnit": "unit",
            "replaced": false,
            "returned": true
          },
          {
            "itemId": "12346",
            "scanCode": "00980349941",
            "quantityRequested": 2.0,
            "quantityRequestedUnit": "unit",
            "quantityFulfilled": 1.0,
            "quantityFulfilledUnit": "unit",
            "replaced": true,
            "replacement": {
              "itemId": "12345"
            },
            "returned": true
          },
          {
            "itemId": "12347",
            "scanCode": "",
            "quantityRequested": 5.0,
            "quantityRequestedUnit": "unit",
            "quantityFulfilled": 0.430,
            "quantityFulfilledUnit": "kilograms",
            "replaced": true,
            "replacement": {
              "itemId": "12",
              "shopperProvidedName": "Oranges",
              "shopperProvidedPrice": 1.23
            },
            "returned": true
          }
        ]
      }
    }
    ```

servers:
  - url: https://api.example.com/retailer/v1
    description: Production server (live data)
  - url: https://sandbox-api.example.com/v1
    description: Sandbox server (test data)

tags:
  - name: auth
  - name: service-availability
  - name: picking-locations
  - name: timeslots
  - name: orders
  - name: webhooks

paths:
  # Authentication
  /oauth/token:
    $ref: "./paths/auth/post-token.yaml"
  /oauth/token/revoke:
    $ref: "./paths/auth/post-token-revoke.yaml"

  # Service availability
  /service-availability:
    $ref: "./paths/service-availability/get.yaml"
    
  # Picking Locations
  /picking-locations:
    $ref: "./paths/picking-locations/picking-locations.yaml"
  /picking-locations/{id}: 
    $ref: "./paths/picking-locations/picking-locations-id.yaml"
  /picking-locations/{id}/schedule:
    $ref: "./paths/picking-locations/picking-locations-schedule.yaml"

  # Timeslots
  /timeslots:
    $ref: "./paths/timeslots/timeslots.yaml"
  /timeslots/{id}/reservations:
    $ref: "./paths/timeslots/timeslots-reservations.yaml"
  /timeslots/{timeslotId}/reservations/{reservationId}/cancel:
    $ref: "./paths/timeslots/timeslots-reservations-cancel.yaml"

  # Orders
  /orders:
    $ref: "./paths/orders/orders.yaml"
  /orders/{id}:
    $ref: "./paths/orders/orders-id.yaml"
  /orders/{id}/cancel:
    $ref: "./paths/orders/orders-id-cancel.yaml"

  # Webhooks
  /webhooks/subscriptions/event-types:
    $ref: "./paths/webhooks/subscriptions-event-types.yaml"
  /webhooks/subscriptions:
    $ref: "./paths/webhooks/subscriptions.yaml"
  /webhooks/subscriptions/{id}:
    $ref: "./paths/webhooks/subscriptions-id.yaml"
  /webhooks/subscriptions/{id}/test:
    $ref: "./paths/webhooks/subscriptions-id-test.yaml"

components:
  schemas:
    $ref: "./schemas/_index.yaml"
